language: php
sudo: false
php:
  - '5.5'
  - '5.6'
  - '7.0'
before_install:
    - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit
  - output=$(vendor/bin/php-cs-fixer fix -v --dry-run .); if [[ $output ]]; then while read -r line; do echo -e "\e[00;31m$line\e[00m"; done <<< "$output"; false; fi;
