language: php
sudo: false
php:
  - '7.3'
  - '7.4'
before_install:
    - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls -v
