name:          phpSmug
domain:        phpsmug.com    # This is used by the Analytics tracking code
description:   PHP wrapper for the SmugMug API
url:           http://phpsmug.com
author:        Colin Seymour (@lildude)
analytics_id:  UA-118457-4
timezone:      Europe/London
encoding:      UTF-8
baseurl:       ""
permalink:     /news/:title/
latest_version: 4.0.0
gems:
  - jemoji
  - jekyll-sitemap
markdown:      kramdown
highlighter:   rouge
kramdown:
  input: GFM
  
#markdown:     redcarpet
#redcarpet:
#  extensions: ["autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks", "disable_indented_code_blocks"]

# Hard code our nav here to keep things in order and precisely as we want
navigation:
  - title: Overview
    url: /
  - title: Documentation
    url: /docs/
  - title: Download
    url: /download/
  - title: News
    url: /news/
  - title: About
    url: /about/
